OPCODE(CONSTANT, 1)

OPCODE(CONSTANT_LONG, 1)

OPCODE(ADD, -1)
OPCODE(SUBTRACT, -1)
OPCODE(NEGATE, -1)
OPCODE(MULTIPLY, -1)
OPCODE(DIVIDE, -1)

OPCODE(NIL, 1)
OPCODE(TRUE, 1)
OPCODE(FALSE, 1)

OPCODE(PRINT, 0)

OPCODE(POP, -1)

OPCODE(DEFINE_GLOBAL, 1)
OPCODE(GET_GLOBAL, -1)
OPCODE(SET_GLOBAL, -1)
OPCODE(GET_LOCAL, -1)
OPCODE(SET_LOCAL, -1)

OPCODE(JUMP_IF, -1)
OPCODE(JUMP, 0)
OPCODE(LOOP, 0)

OPCODE(CALL, 0)

OPCODE(RETURN, -1)
